name: CI Pipeline

on:
  pull_request:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install env
        uses: ./.github/install_python_env

      - name: Lint
        run: |
          source .venv/bin/activate
          make lint

      - name: Unit test
        shell: bash
        env:
          CAR_CUTTER_FILE_STORE_BASE_DIR: $PWD
        run: |
          source .venv/bin/activate
          make unit-test

      - name: Acceptance test
        shell: bash
        env:
          CAR_CUTTER_FILE_STORE_BASE_DIR: $PWD
        run: |
          source .venv/bin/activate
          make acceptance-test
